---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "visilitator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: visilitator
    app.kubernetes.io/instance: visilitator
data:
  RELEASE_NAME: "visilitator"
  RELEASE_TMP: "/tmp"
  PROBE_PORT: "9090"
  RABBITMQ_HOST: {{ include "rabbitmq.hostname" . }}