---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "visilitator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: visilitator
    app.kubernetes.io/instance: visilitator