name: Sobelow

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '43 0 * * 1'
permissions:
  contents: read
jobs:
  security-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - id: run-action
        uses: sobelow/action@v1
      - name: Upload report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif